"""Properties of the 20 standard amino acids."""

from typing import Dict

AMINO_ACID_PROPERTIES: Dict[str, Dict] = {
    "A": {
        "full_name": "Alanine",
        "three_letter": "Ala",
        "molecular_weight": 89.09,
        "charge": "neutral",
        "polarity": "nonpolar",
        "hydrophobicity": "hydrophobic",
        "classification": "nonpolar_aliphatic",
    },
    "R": {
        "full_name": "Arginine",
        "three_letter": "Arg",
        "molecular_weight": 174.20,
        "charge": "positive",
        "polarity": "polar",
        "hydrophobicity": "hydrophilic",
        "classification": "positively_charged",
    },
    "N": {
        "full_name": "Asparagine",
        "three_letter": "Asn",
        "molecular_weight": 132.12,
        "charge": "neutral",
        "polarity": "polar",
        "hydrophobicity": "hydrophilic",
        "classification": "polar_uncharged",
    },
    "D": {
        "full_name": "Aspartic acid",
        "three_letter": "Asp",
        "molecular_weight": 133.10,
        "charge": "negative",
        "polarity": "polar",
        "hydrophobicity": "hydrophilic",
        "classification": "negatively_charged",
    },
    "C": {
        "full_name": "Cysteine",
        "three_letter": "Cys",
        "molecular_weight": 121.16,
        "charge": "neutral",
        "polarity": "polar",
        "hydrophobicity": "hydrophobic",
        "classification": "special",
    },
    "E": {
        "full_name": "Glutamic acid",
        "three_letter": "Glu",
        "molecular_weight": 147.13,
        "charge": "negative",
        "polarity": "polar",
        "hydrophobicity": "hydrophilic",
        "classification": "negatively_charged",
    },
    "Q": {
        "full_name": "Glutamine",
        "three_letter": "Gln",
        "molecular_weight": 146.15,
        "charge": "neutral",
        "polarity": "polar",
        "hydrophobicity": "hydrophilic",
        "classification": "polar_uncharged",
    },
    "G": {
        "full_name": "Glycine",
        "three_letter": "Gly",
        "molecular_weight": 75.03,
        "charge": "neutral",
        "polarity": "nonpolar",
        "hydrophobicity": "neutral",
        "classification": "special",
    },
    "H": {
        "full_name": "Histidine",
        "three_letter": "His",
        "molecular_weight": 155.16,
        "charge": "positive",
        "polarity": "polar",
        "hydrophobicity": "hydrophilic",
        "classification": "positively_charged",
    },
    "I": {
        "full_name": "Isoleucine",
        "three_letter": "Ile",
        "molecular_weight": 131.17,
        "charge": "neutral",
        "polarity": "nonpolar",
        "hydrophobicity": "hydrophobic",
        "classification": "nonpolar_aliphatic",
    },
    "L": {
        "full_name": "Leucine",
        "three_letter": "Leu",
        "molecular_weight": 131.17,
        "charge": "neutral",
        "polarity": "nonpolar",
        "hydrophobicity": "hydrophobic",
        "classification": "nonpolar_aliphatic",
    },
    "K": {
        "full_name": "Lysine",
        "three_letter": "Lys",
        "molecular_weight": 146.19,
        "charge": "positive",
        "polarity": "polar",
        "hydrophobicity": "hydrophilic",
        "classification": "positively_charged",
    },
    "M": {
        "full_name": "Methionine",
        "three_letter": "Met",
        "molecular_weight": 149.21,
        "charge": "neutral",
        "polarity": "nonpolar",
        "hydrophobicity": "hydrophobic",
        "classification": "nonpolar_aliphatic",
    },
    "F": {
        "full_name": "Phenylalanine",
        "three_letter": "Phe",
        "molecular_weight": 165.19,
        "charge": "neutral",
        "polarity": "nonpolar",
        "hydrophobicity": "hydrophobic",
        "classification": "aromatic",
    },
    "P": {
        "full_name": "Proline",
        "three_letter": "Pro",
        "molecular_weight": 115.13,
        "charge": "neutral",
        "polarity": "nonpolar",
        "hydrophobicity": "neutral",
        "classification": "special",
    },
    "S": {
        "full_name": "Serine",
        "three_letter": "Ser",
        "molecular_weight": 105.09,
        "charge": "neutral",
        "polarity": "polar",
        "hydrophobicity": "hydrophilic",
        "classification": "polar_uncharged",
    },
    "T": {
        "full_name": "Threonine",
        "three_letter": "Thr",
        "molecular_weight": 119.12,
        "charge": "neutral",
        "polarity": "polar",
        "hydrophobicity": "hydrophilic",
        "classification": "polar_uncharged",
    },
    "W": {
        "full_name": "Tryptophan",
        "three_letter": "Trp",
        "molecular_weight": 204.23,
        "charge": "neutral",
        "polarity": "nonpolar",
        "hydrophobicity": "hydrophobic",
        "classification": "aromatic",
    },
    "Y": {
        "full_name": "Tyrosine",
        "three_letter": "Tyr",
        "molecular_weight": 181.19,
        "charge": "neutral",
        "polarity": "polar",
        "hydrophobicity": "neutral",
        "classification": "aromatic",
    },
    "V": {
        "full_name": "Valine",
        "three_letter": "Val",
        "molecular_weight": 117.15,
        "charge": "neutral",
        "polarity": "nonpolar",
        "hydrophobicity": "hydrophobic",
        "classification": "nonpolar_aliphatic",
    },
}
